services:
  mind-share-api:
    env_file:
      - ./api/mind-share-api/env/local.env
    image: mind-share-api:latest
    build:
      context: .
      dockerfile: api/mind-share-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mind-share
  db:
    image: mind-share-db:latest
    build:
      context: .
      dockerfile: db/mysql/Dockerfile
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - mind-share
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - mind-share
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 10s
networks:
  mind-share:
    driver: bridge
