spring:
  application:
    name: mind-share
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: false
  datasource:
    hikari:
      maximum-pool-size: 51 # pool size = Tn * (Cn - 1) + 1, [Tn: ?? ??? ??, Cn: ? Task ?? ??? ??? Connection ?]
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
  data:
    redis:
      host: ${REDIS_HOST}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

auth:
  secret-key: ${JWT_SECRET}
  access-token-ttl: ${ACCESS_TOKEN_TTL}
  refresh-token-ttl: ${REFRESH_TOKEN_TTL}