CREATE TABLE ACCOUNT
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    USER_ID          BIGINT       NOT NULL COMMENT 'User ID',
    LOGIN_ID         VARCHAR(255) NOT NULL COMMENT 'Login ID',
    CREDENTIAL       VARCHAR(255) NOT NULL COMMENT 'Credential',
    ACCOUNT_PROVIDER VARCHAR(255) NOT NULL COMMENT 'Account Provider',
    CT_UTC           TIMESTAMP    NOT NULL COMMENT 'Creation Time',
    UT_UTC           TIMESTAMP    NOT NULL COMMENT 'Update Time',
    UNIQUE (LOGIN_ID, ACCOUNT_PROVIDER)
);

CREATE INDEX IDX_ACCOUNT_USER_ID ON ACCOUNT (USER_ID);

CREATE TABLE AUTH_REFRESH_TOKEN
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    USER_ID         BIGINT       NOT NULL COMMENT 'User ID',
    SESSION_ID      VARCHAR(255) NOT NULL UNIQUE COMMENT 'Session ID',
    EXPIRATION_TIME TIMESTAMP    NOT NULL COMMENT 'Expiration Time',
    TOKEN           VARCHAR(255) NOT NULL COMMENT 'Refresh Token Value',
    CT_UTC          TIMESTAMP    NOT NULL COMMENT 'Creation Time',
    UT_UTC          TIMESTAMP    NOT NULL COMMENT 'Update Time'
);

CREATE INDEX IDX_REFRESH_TOKEN_USER_ID ON AUTH_REFRESH_TOKEN (USER_ID);
