CREATE TABLE POST
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Id',
    USER_ID BIGINT       NOT NULL COMMENT 'User Id',
    TITLE   VARCHAR(30)  NOT NULL COMMENT 'Post Title',
    CONTENT VARCHAR(250) NOT NULL COMMENT 'Post Content',
    CT_UTC  TIMESTAMP    NOT NULL COMMENT 'Creation Time',
    UT_UTC  TIMESTAMP    NOT NULL COMMENT 'Update Time',
    FULLTEXT INDEX FT_TITLE_CONTENT (TITLE, CONTENT)
);

CREATE INDEX IDX_POST_CT_UTC_USER_ID ON POST(CT_UTC, USER_ID);
CREATE INDEX IDX_POST_USER_ID ON POST(USER_ID);

CREATE TABLE POST_INTERACTION
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Id',
    POST_ID BIGINT              NOT NULL COMMENT 'Post Id',
    TYPE    ENUM ('VIEW_COUNT') NOT NULL COMMENT 'Post Interaction Type',
    COUNT   BIGINT              NOT NULL COMMENT 'Post Interaction Count'
);

CREATE INDEX IDX_POST_INTERACTION_POST_ID_TYPE ON POST_INTERACTION(POST_ID, TYPE);